const CLOTHING_SIZE_SCALE = {
    XS: 0.82,
    S: 0.9,
    M: 1,
    L: 1.12,
    XL: 1.24,
    XXL: 1.36,
  };
  
  const SHOE_SIZE_SCALE = {
    38: 0.86,
    39: 0.9,
    40: 0.94,
    41: 0.97,
    42: 1,
    43: 1.04,
    44: 1.08,
    45: 1.12,
    46: 1.16,
    47: 1.2,
  };
  
  const PACKING_ITEM_PROFILES = {
    tshirt_basic: {
      key: "tshirt_basic",
      aliases: ["t-shirt", "t shirt", "shirt", "tee", "tshirt"],
      category: "clothing",
      base: {
        dimensionsCm: { w: 16, h: 4, d: 11 },
        weightG: 180,
        materialType: "soft",
        rigidityScore: 8,
        compressibilityScore: 82,
        stackabilityScore: 88,
        preferredOrientations: ["flat"],
        allowedOrientations: ["flat", "rolled"],
        renderHint: { shape: "folded_cloth", colorToken: "clothing", icon: "shirt" },
        foldStyle: "flat",
      },
      sizeType: "clothing",
    },
  
    pants_basic: {
      key: "pants_basic",
      aliases: ["pants", "trousers", "jeans"],
      category: "bottoms",
      base: {
        dimensionsCm: { w: 18, h: 4, d: 12 },
        weightG: 420,
        materialType: "soft",
        rigidityScore: 16,
        compressibilityScore: 62,
        stackabilityScore: 80,
        preferredOrientations: ["flat"],
        allowedOrientations: ["flat"],
        renderHint: { shape: "folded_cloth", colorToken: "clothing", icon: "pants" },
        foldStyle: "flat",
      },
      sizeType: "clothing",
    },
  
    hoodie_bulky: {
      key: "hoodie_bulky",
      aliases: ["hoodie", "sweatshirt", "pullover"],
      category: "outerwear",
      base: {
        dimensionsCm: { w: 22, h: 8, d: 15 },
        weightG: 650,
        materialType: "soft",
        rigidityScore: 18,
        compressibilityScore: 48,
        stackabilityScore: 72,
        preferredOrientations: ["flat"],
        allowedOrientations: ["flat"],
        renderHint: { shape: "folded_cloth", colorToken: "clothing", icon: "hoodie" },
        foldStyle: "flat",
      },
      sizeType: "clothing",
    },
  
    underwear_basic: {
      key: "underwear_basic",
      aliases: ["underwear", "boxers", "briefs"],
      category: "underwear",
      base: {
        dimensionsCm: { w: 7, h: 4, d: 6 },
        weightG: 60,
        materialType: "soft",
        rigidityScore: 4,
        compressibilityScore: 92,
        stackabilityScore: 90,
        preferredOrientations: ["rolled"],
        allowedOrientations: ["rolled", "flat"],
        renderHint: { shape: "soft_roll", colorToken: "underwear", icon: "roll" },
        foldStyle: "rolled",
      },
      sizeType: "clothing",
    },
  
    socks_basic: {
      key: "socks_basic",
      aliases: ["socks", "sock"],
      category: "underwear",
      base: {
        dimensionsCm: { w: 6, h: 3, d: 5 },
        weightG: 40,
        materialType: "soft",
        rigidityScore: 3,
        compressibilityScore: 94,
        stackabilityScore: 92,
        preferredOrientations: ["rolled"],
        allowedOrientations: ["rolled", "flat"],
        renderHint: { shape: "soft_roll", colorToken: "underwear", icon: "roll" },
        foldStyle: "rolled",
      },
      sizeType: "none",
    },
  
    shoes_standard_pair: {
      key: "shoes_standard_pair",
      aliases: ["shoes", "sneakers", "trainers"],
      category: "shoes",
      base: {
        dimensionsCm: { w: 18, h: 11, d: 13 },
        weightG: 950,
        materialType: "rigid",
        rigidityScore: 86,
        compressibilityScore: 6,
        stackabilityScore: 42,
        preferredOrientations: ["flat"],
        allowedOrientations: ["flat"],
        renderHint: { shape: "shoe_box", colorToken: "shoes", icon: "shoe" },
        foldStyle: "none",
      },
      sizeType: "shoes",
    },
  
    toiletries_pouch: {
      key: "toiletries_pouch",
      aliases: ["toiletries", "toiletry pouch", "toothbrush", "toothpaste"],
      category: "toiletries",
      base: {
        dimensionsCm: { w: 16, h: 6, d: 10 },
        weightG: 350,
        materialType: "semi_soft",
        rigidityScore: 36,
        compressibilityScore: 28,
        stackabilityScore: 65,
        preferredOrientations: ["flat"],
        allowedOrientations: ["flat"],
        renderHint: { shape: "rounded_box", colorToken: "toiletries", icon: "pouch" },
        foldStyle: "none",
      },
      sizeType: "none",
    },
  
    passport_flat: {
      key: "passport_flat",
      aliases: ["passport", "documents", "document", "papers"],
      category: "documents",
      base: {
        dimensionsCm: { w: 12, h: 2, d: 9 },
        weightG: 80,
        materialType: "semi_soft",
        rigidityScore: 22,
        compressibilityScore: 18,
        stackabilityScore: 84,
        preferredOrientations: ["flat"],
        allowedOrientations: ["flat"],
        renderHint: { shape: "flat_document", colorToken: "documents", icon: "document" },
        foldStyle: "none",
      },
      sizeType: "none",
    },
  
    charger_small: {
      key: "charger_small",
      aliases: ["charger", "power bank", "adapter", "cable"],
      category: "tech",
      base: {
        dimensionsCm: { w: 9, h: 4, d: 7 },
        weightG: 180,
        materialType: "semi_soft",
        rigidityScore: 48,
        compressibilityScore: 10,
        stackabilityScore: 66,
        preferredOrientations: ["flat"],
        allowedOrientations: ["flat"],
        renderHint: { shape: "compact_box", colorToken: "tech", icon: "tech" },
        foldStyle: "none",
      },
      sizeType: "none",
    },
  
    tech_generic: {
      key: "tech_generic",
      aliases: ["tech", "electronics", "headphones"],
      category: "tech",
      base: {
        dimensionsCm: { w: 13, h: 4, d: 9 },
        weightG: 260,
        materialType: "semi_soft",
        rigidityScore: 56,
        compressibilityScore: 8,
        stackabilityScore: 58,
        preferredOrientations: ["flat"],
        allowedOrientations: ["flat"],
        renderHint: { shape: "compact_box", colorToken: "tech", icon: "tech" },
        foldStyle: "none",
      },
      sizeType: "none",
    },
  
    accessories_basic: {
      key: "accessories_basic",
      aliases: ["accessories", "belt", "sunglasses", "cap"],
      category: "accessories",
      base: {
        dimensionsCm: { w: 9, h: 4, d: 7 },
        weightG: 120,
        materialType: "soft",
        rigidityScore: 20,
        compressibilityScore: 55,
        stackabilityScore: 72,
        preferredOrientations: ["flat"],
        allowedOrientations: ["flat", "rolled"],
        renderHint: { shape: "small_box", colorToken: "accessories", icon: "accessory" },
        foldStyle: "auto",
      },
      sizeType: "none",
    },
  
    misc_generic: {
      key: "misc_generic",
      aliases: [],
      category: "misc",
      base: {
        dimensionsCm: { w: 12, h: 5, d: 9 },
        weightG: 220,
        materialType: "semi_soft",
        rigidityScore: 34,
        compressibilityScore: 30,
        stackabilityScore: 60,
        preferredOrientations: ["flat"],
        allowedOrientations: ["flat"],
        renderHint: { shape: "rounded_box", colorToken: "misc", icon: "item" },
        foldStyle: "auto",
      },
      sizeType: "none",
    },
  };
  
  module.exports = {
    PACKING_ITEM_PROFILES,
    CLOTHING_SIZE_SCALE,
    SHOE_SIZE_SCALE,
  };